spring.application.name=auth-service
server.port=4005

# When running in Docker, use service name
spring.datasource.url=jdbc:postgresql://auth-db:5432/auth-service-db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=120000

jwt.secret=Y2hhVEc3aHJnb0hYTzMyZ2ZqVkpiZ1RkZG93YWxrUkM=

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html