spring.application.name=patient-service
server.port=4000

# When running in Docker, use service names
spring.datasource.url=jdbc:postgresql://patient-db:5432/patient-service-db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=120000

billing.service.address=billing-service
billing.service.grpc.port=9001

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.bootstrap-servers=kafka:9092

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.root=info